option(WITH_STATIC_LIBRARY "Build with a static library" OFF)
option(WITH_UNIT_TESTS "Build unit tests" ON)
option(WITH_CXX "Build the C++ library" OFF)
option(INTERNAL_WITH_GCOV "Build with test coverage instrumentation" OFF)
mark_as_advanced(INTERNAL_WITH_GCOV)
