#!/bin/bash
#
# Script to accept the current output for some output comparing test as the golden output
#
#   Usage: accept <test> <lang>
#
# Will copy build/build-<lang>/tests/<test>.output to tests/<test>.<lang>.expected

if [ "$#" -ne 2 ]
then
  echo "Usage: accept <test> <lang>"
  exit 1
fi

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
rootdir=$(dirname $scriptdir)

echo "About to 'cp build/build-$2/tests/$1.output tests/$1.$2.expected'"

read -r -p "Are you sure? [y/N] " response
if [[ ! $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
    exit
fi

cp $rootdir/build/build-$2/tests/$1.output $rootdir/tests/$1.$2.expected
echo "Copied!"