#!/bin/sh
#
# Will run the cgreen-runner in directory $1
# on library $2
# store the output in $3.output,
# compare it with expected output in $4
# but run the SED commands in $5 and onwards on the output before doing the comparison
runner_dir=$1
lib=$2
name=$3
expected=$4

if [ -z "$CGREEN_PER_TEST_TIMEOUT" ]; then
    echo "Comparing output of $2 to expected"
else
    echo "Comparing output of $2 to expected with CGREEN_PER_TEST_TIMEOUT=$CGREEN_PER_TEST_TIMEOUT"
fi

# Run runner on library store output and error
${runner_dir}/cgreen-runner ${lib} > ${name}.output 2> ${name}.error
cat ${name}.error >> ${name}.output

tempfile=`mktemp`

# - line numbers in error messages
echo "s/:[0-9]+:/:/g" > $tempfile

# - timing info
echo "s/in [0-9]+ms\./in 0ms\./g" >> $tempfile

# - library prefix
echo s/\".*${name}\"/\"${name}\"/g >> $tempfile

# Execute some extra SED commands in $5 and onwards on the output
shift 4
for sedcommand in $@ ; do
    echo ${sedcommand} >> $tempfile
done

sed -E -f $tempfile ${name}.output > ${name}.output.tmp
mv ${name}.output.tmp ${name}.output

# Compare output to expected
cmp --silent ${name}.output ${expected}

# If not the same, show diff
rc=$?; if [ $rc -ne 0 ]; then diff -c ${expected} ${name}.output ; fi
exit $rc
