#! /bin/sh
#
# Will run the cgreen-runner in directory $1
# on library $2
# store the output in $3.output,
# compare it with expected output in $4
# but run the SED commands in $5 and onwards on the output before doing the comparison
runner_dir=$1
lib=$2
name=$3
expected=$4

# Run runner on library store output
${runner_dir}/cgreen-runner ${lib} > ${name}.output

shift 4
# Execute some SED command in $5 and onwards on the output
for sedcommand in $@ ; do
    echo sed -E -e ${sedcommand} ${name}.output ${name}.output.tmp
    sed -E -e ${sedcommand} ${name}.output > ${name}.output.tmp
    mv ${name}.output.tmp ${name}.output
done

# Compare output to expected
cmp --silent ${name}.output ${expected}

# If not the same, show diff
rc=$?; if [ $rc -ne 0 ]; then diff -c ${name}.output ${expected} ; fi
exit $rc

             
