#! /bin/sh
#
# Will run the cgreen-runner in directory $1
# on library $2
# store the output in $3.output,
# compare it with expected output in $4
# but remove $5.. from the output before doing the comparison
runner_dir=$1
lib=$2
name=$3
expected=$4

# Run runner on library, strip absolute file path from output and store it
${runner_dir}/cgreen-runner ${lib} > ${name}.output

shift 4
# Remove strings in $5 and onwards from the output
for r in $@ ; do
    echo sed -e s%$r%%g ${name}.output ${name}.output.tmp
    sed -e s%$r%%g ${name}.output > ${name}.output.tmp
    cp ${name}.output.tmp ${name}.output
done

# Compare output from expected
cmp --silent ${name}.output ${expected}

# If not the same show diff
rc=$?; if [ $rc -ne 0 ]; then diff -c ${name}.output ${expected} ; fi
exit $rc

                 
