#! /bin/sh
#
# Will run cgreen-runner in directory $1
# on the library $2,
# remove $3 from the output and then
# store the output in $4.output,
# compare it with $4.expected,
# which can be found in directory $5

# Run runner on library, strip absolute file path from output and store it
$1/cgreen-runner $2 | sed -e s#$3/##g > $4.output
# Compare output from expected in some dir ($5)
cmp --silent $4.output $5/$4.expected
# If not the same show diff
rc=$?; if [ $rc -ne 0 ]; then diff -c $4.output $5/$4.expected ; fi
exit $rc
